simplify boilerplate with new helpers, ops
hydro-project/hydroflow pull request #282
Opened 2022-12-07 08:14 UTC by jhellerstein

first cut. 

One concern is that recv_udp(0) doesn't have a way to tell us what port it ended up getting.

2022-12-07 22:19 UTC, MingweiSamuel requested changes

2022-12-07 22:19 UTC, MingweiSamuel commented on hydroflow_lang/src/graph/ops/recv_stdin.rs
> +///     recv_stdin -> map(|x| x.to_uppercase())
`recv_stdin()`

2022-12-07 22:19 UTC, MingweiSamuel commented on hydroflow_lang/src/graph/ops/recv_udp.rs
> +/// `recv_net` binds to a local network port and receives a Stream of serialized data from a remote sender,
`recv_udp`?

2022-12-07 22:19 UTC, MingweiSamuel commented on hydroflow_lang/src/graph/ops/recv_udp.rs
> +///     recv_net(9000) -> map(|x| x.to_uppercase())
`recv_udp(9000)`

2022-12-08 01:28 UTC, jhellerstein commented on hydroflow/examples/echoserver/client.rs
>  use tokio::net::UdpSocket;
don't seem to be able to remove this despite the change above. let's try together

2022-12-09 17:42 UTC, MingweiSamuel approved these changes
LGTM. I think we will rename `sink_async_serde`/`recv_stream_serde` as part of #276 / #216

2022-12-09 18:46 UTC, merged