Support more aggregations and comments in Dedalus (#254).
hydro-project/hydroflow pull request #426
Opened 2023-03-01 23:26 UTC by davidchuyaya

2023-03-01 23:40 UTC, MingweiSamuel commented on hydroflow_datalog_core/src/lib.rs
> +                            parse_quote!(prev) // choose = select any 1 element from the relation. By default we select the 1st.
this seems a little to deterministic

2023-03-01 23:44 UTC, davidchuyaya commented on hydroflow_datalog_core/src/lib.rs
> +                            parse_quote!(prev) // choose = select any 1 element from the relation. By default we select the 1st.
that's ok tho

2023-03-02 08:15 UTC, shadaj requested changes

2023-03-02 08:15 UTC, shadaj commented on hydroflow_datalog_core/examples/voting/leader.dl
> +.input clientIn
If these aren't being used in any actual tests we should probably drop them for now.

2023-03-02 08:15 UTC, shadaj commented on hydroflow_datalog_core/src/lib.rs
> +            clientOut@addr(choose(i)) :~ clientIn(i), clientAddr(addr)
Can we add runtime tests for this and count? Doesn't need to be a full Dedalus test, we can just run in Datalog + ticks single-node mode.

2023-03-03 21:30 UTC, MingweiSamuel commented
Looks like some of Shadaj's commits snuck in?

2023-03-03 21:37 UTC, davidchuyaya commented
> 

Yeah it's based off `deploy-custom-services` since that was my local branch

2023-03-03 23:33 UTC, shadaj commented
@davidchuyaya can you rebase when you get a chance, that branch has been merged in

2023-03-15 00:52 UTC, closed without merging

2023-03-15 00:53 UTC, MingweiSamuel commented
Hmm